# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [60]:
# Completar o exercício aqui
import numpy as np
from numpy import random
elementos_10_100 = np.arange(10,101)
elementos_10_100_reverse = elementos_10_100[::-1]
print("elementos (de 10 a 100) invertido: ",elementos_10_100_reverse,"\n")

elementos_0_8 = np.array([(4,3,1),(6,1,1)])
identidade = np.array([(6,6,2,5,5,8),(9,5,2,6,3,1)])
random_geretor = random.default_rng()
array_aleatorio = random_geretor.integers(low=1,high=10,size=(3,3))
print("identidade de 6x6:\n",identidade,"\n")
print("array 3x3 com valores de 0 a 8:\n",elementos_0_8,"\n")
print("array com valores aleatórios com o formato 3x3x3:\n",array_aleatorio,"\n")

array_A = random_geretor.integers(low=1,high=10,size=1)
array_B = random_geretor.integers(low=1,high=10,size=1)
if array_A == array_B:
    print("O Array A e igual ao Array B")
else: print("Os Arrays A e B sao diferentes")
print("Array A",array_A,"|| Array B",array_B)

elementos (de 10 a 100) invertido:  [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10] 

identidade de 6x6:
 [[6 6 2 5 5 8]
 [9 5 2 6 3 1]] 

array 3x3 com valores de 0 a 8:
 [[4 3 1]
 [6 1 1]] 

array com valores aleatórios com o formato 3x3x3:
 [[2 3 9]
 [9 7 9]
 [9 4 3]] 

Os Arrays A e B sao diferentes
Array A [8] || Array B [6]


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Criar outro array chamado euros
* Fazer a conversão dos preços em dólares do primeiro array ao segundo array em euros. Pode-se utilizar a seguinte conversão: 
  - 1 EUR = 1,14362 USD
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, mas arredondado a 2 décimas

In [15]:
# Completar o exercício aqui
import numpy as np
from numpy import random
gerador_aleatorio = random.default_rng()
dolares = gerador_aleatorio.integers(low=1,high=1000,size=100)
euros = gerador_aleatorio.integers(low=1,high=1000,size=100)
list_dolares=[]
list_euros=[]
print(f"Euros a converter:\n{euros}")
for dolar in dolares:
    dolar = "{:.2f}".format(dolar*0.874413)
    list_dolares.append(dolar)
    dolares = np.array(list_dolares)
for euro in euros:
    euro = "{:.2f}".format(euro*1.14362)
    list_euros.append(euro)
    euros = np.array(list_euros)


print("\nEuros convertidos:\n",euros)

Euros a converter:
[875 100 326  28 278 954 633 775  85  55 653 968 687 857 368 347 725 692
 474 711 709 140 235 685 473 292 392 685  74 736 403 195 684 910 420 397
 717 326 398 360 169 917 823 179  65 798 957 721 428 656 767 501 379 308
 254 739 334 116 818 995 878 863 637 157 619 472  47  94 895 532 781 977
 165 831 181  44 387   6 637 720 527 477 306 334 943 730 732 579 227 300
 216  48 612 936 293 551 252 920 483 717]

Euros convertidos:
 ['1000.67' '114.36' '372.82' '32.02' '317.93' '1091.01' '723.91' '886.31'
 '97.21' '62.90' '746.78' '1107.02' '785.67' '980.08' '420.85' '396.84'
 '829.12' '791.39' '542.08' '813.11' '810.83' '160.11' '268.75' '783.38'
 '540.93' '333.94' '448.30' '783.38' '84.63' '841.70' '460.88' '223.01'
 '782.24' '1040.69' '480.32' '454.02' '819.98' '372.82' '455.16' '411.70'
 '193.27' '1048.70' '941.20' '204.71' '74.34' '912.61' '1094.44' '824.55'
 '489.47' '750.21' '877.16' '572.95' '433.43' '352.23' '290.48' '845.14'
 '381.97' '132.66' '935.48' '1137.90' '10

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos
* Carregar como dataframe de pandas o csv 05_05_imdb_titulos.csv e mostrar os seus 5 primeiros registos 
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos 
* Mostrar o número de registos da dataframe de títulos
* Mostrar o número de registos do dataframe de elenco 
* Mostrar as 5 filmes mais antigas da listagem de títulos
* Mostrar as filmes que no título têm a palavra “Dracula”. Também mostrar o número total de filmes que coincidam com este requisito
* Mostrar os 10 títulos mais comuns (que mais se repetem)
* Mostrar qual foi a primeira película feita intitulada “Romeo and Juliet”
* Listar todas as filmes que contenham a palavra “Exorcist” ordenadas da mais velha à mais recente 
* Mostrar quantas filmes foram feitas no ano 1950
* Mostrar quantas filmes foram feitas de 1950 a 1959
* Mostrar todos os papéis que teve na película “The Godfather”. Também mostrar o número total de coincidências 
* Mostrar o elenco completo ordenado pela classificação “n” da película “Dracula” de 1958
* Mostrar quantos papéis de “Bruce Wayne” têm sido feitos na história das filmes 
* Mostrar quantos papéis fez o “Robert De Niro” na sua carreira
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década 60, ordenado por ano de forma descendente
* Mostrar quantos papéis para atores houve na década 50 
* Mostrar quantos papéis para atrizes houve na década 50

In [16]:
# Completar o exercício aqui
import pandas
pandas.read_csv()

'1.4.2'