# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [60]:
# Completar o exercício aqui
import numpy as np
from numpy import random
elementos_10_100 = np.arange(10,101)
elementos_10_100_reverse = elementos_10_100[::-1]
print("elementos (de 10 a 100) invertido: ",elementos_10_100_reverse,"\n")

elementos_0_8 = np.array([(4,3,1),(6,1,1)])
identidade = np.array([(6,6,2,5,5,8),(9,5,2,6,3,1)])
random_geretor = random.default_rng()
array_aleatorio = random_geretor.integers(low=1,high=10,size=(3,3))
print("identidade de 6x6:\n",identidade,"\n")
print("array 3x3 com valores de 0 a 8:\n",elementos_0_8,"\n")
print("array com valores aleatórios com o formato 3x3x3:\n",array_aleatorio,"\n")

array_A = random_geretor.integers(low=1,high=10,size=1)
array_B = random_geretor.integers(low=1,high=10,size=1)
if array_A == array_B:
    print("O Array A e igual ao Array B")
else: print("Os Arrays A e B sao diferentes")
print("Array A",array_A,"|| Array B",array_B)

elementos (de 10 a 100) invertido:  [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10] 

identidade de 6x6:
 [[6 6 2 5 5 8]
 [9 5 2 6 3 1]] 

array 3x3 com valores de 0 a 8:
 [[4 3 1]
 [6 1 1]] 

array com valores aleatórios com o formato 3x3x3:
 [[2 3 9]
 [9 7 9]
 [9 4 3]] 

Os Arrays A e B sao diferentes
Array A [8] || Array B [6]


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Criar outro array chamado euros
* Fazer a conversão dos preços em dólares do primeiro array ao segundo array em euros. Pode-se utilizar a seguinte conversão: 
  - 1 EUR = 1,14362 USD
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, mas arredondado a 2 décimas

In [4]:
# Completar o exercício aqui
import numpy as np
from numpy import random
gerador_aleatorio = random.default_rng()
dolares = gerador_aleatorio.integers(low=1,high=1000,size=100)
euros = gerador_aleatorio.integers(low=1,high=1000,size=100)
list_dolares=[]
list_euros=[]
print(f"Euros a converter:\n{euros}")
for dolar in dolares:
    dolar = "{:.2f}".format(dolar*0.874413)
    list_dolares.append(float(dolar))
    dolares = np.array(list_dolares)
for euro in euros:
    euro = "{:.2f}".format(euro*1.14362)
    list_euros.append(float(euro))
    euros = np.array(list_euros)


print("\nEuros convertidos:\n",euros)

Euros a converter:
[ 15 195 518 414 819 894 817 510 823 380 377 248 507 523 109 973 985 473
 129 454 174 336 304 476  81 799 717 232 214 789  85 456 426 947 125 538
 405 679 880 106 768 473 742 125 742 614 539 237 876 792 419 512 140 961
  95 654 724 508 311 526 461 388 595 178 959 699 137 323 236 980 113 417
 589 326 885  66  93 876 876 192 544 243 103 277 774 782 911 119  82 196
 708 296  71 777 775 237 757 865 614 587]

Euros convertidos:
 [  17.15  223.01  592.4   473.46  936.62 1022.4   934.34  583.25  941.2
  434.58  431.14  283.62  579.82  598.11  124.65 1112.74 1126.47  540.93
  147.53  519.2   198.99  384.26  347.66  544.36   92.63  913.75  819.98
  265.32  244.73  902.32   97.21  521.49  487.18 1083.01  142.95  615.27
  463.17  776.52 1006.39  121.22  878.3   540.93  848.57  142.95  848.57
  702.18  616.41  271.04 1001.81  905.75  479.18  585.53  160.11 1099.02
  108.64  747.93  827.98  580.96  355.67  601.54  527.21  443.72  680.45
  203.56 1096.73  799.39  156.68  369.39  2

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos
* Carregar como dataframe de pandas o csv 05_05_imdb_titulos.csv e mostrar os seus 5 primeiros registos 
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos 
* Mostrar o número de registos da dataframe de títulos
* Mostrar o número de registos do dataframe de elenco 
* Mostrar as 5 filmes mais antigas da listagem de títulos
* Mostrar as filmes que no título têm a palavra “Dracula”. Também mostrar o número total de filmes que coincidam com este requisito
* Mostrar os 10 títulos mais comuns (que mais se repetem)
* Mostrar qual foi a primeira película feita intitulada “Romeo and Juliet”
* Listar todas as filmes que contenham a palavra “Exorcist” ordenadas da mais velha à mais recente 
* Mostrar quantas filmes foram feitas no ano 1950
* Mostrar quantas filmes foram feitas de 1950 a 1959
* Mostrar todos os papéis que teve na película “The Godfather”. Também mostrar o número total de coincidências 
* Mostrar o elenco completo ordenado pela classificação “n” da película “Dracula” de 1958
* Mostrar quantos papéis de “Bruce Wayne” têm sido feitos na história das filmes 
* Mostrar quantos papéis fez o “Robert De Niro” na sua carreira
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década 60, ordenado por ano de forma descendente
* Mostrar quantos papéis para atores houve na década 50 
* Mostrar quantos papéis para atrizes houve na década 50

In [24]:
# Completar o exercício aqui
import pandas as pd
import numpy as np

csv_titulos_imdb = pd.read_csv('05_05_imdb_titulos.csv')
elenco_imdb = pd.read_csv('05_05_imdb_elenco.csv')

#Numero de Registos titulos
print(f'\nNumero de Registos Titulos - {len(csv_titulos_imdb)}')
#Numero de Rgistos elenco
print(f'\nNumero de Registos Elenco - {len(elenco_imdb)}')
#Mostrar os 5 primeiros registos de titulos
print(f"\n5 primeiros registros Titulos: \n{csv_titulos_imdb.head(5)}")
#Mostar os 5 ultimos registos de titulo
print(f"\n5 ultimos registros Titulos: \n{csv_titulos_imdb.tail(5)}")
#Mostrar os 5 primeiros registos de elenco
print(f"\n5 primeiros registros Elenco: \n{elenco_imdb.head(5)}")
#Mostrar os 5 ultimos registos de elenco
print(f"\n5 ultimos registros Elenco: \n{elenco_imdb.tail(5)}")
#5 Filmes mais antigos
cinco_filmes_mais_antigos = csv_titulos_imdb.sort_values(by=['year'])[:5]
print(f"\n5 Filmes mais antigos: \n{cinco_filmes_mais_antigos}")

#Filmes com registos "Dracula"
print(f"\n")
filmes_dracula = []
for titulos in csv_titulos_imdb['title']:
    if 'Dracula' == titulos:
        filmes_dracula.append(titulos)
print(f"___Filmes Dracula___\nFilmes: {filmes_dracula}\nTotal de filmes 'Dracula':{len(filmes_dracula)}")

#10 Registos mais comuns
contagem = [{'title':'','count':''}]
pesquisa_de_nome_sort_title = csv_titulos_imdb.sort_values(by=['title'])
for titulos in pesquisa_de_nome_sort_title:
    for data in contagem:
        if titulos != data['title']:
            contagem.append({'title':titulos,'count':1})
        elif titulos == data['title']:
            data['count'] +=1
print(contagem)



#Primeira pelicula 'Romeu e Julieta'
pesquisa_de_nome_sort_ano = csv_titulos_imdb.sort_values(by=['year'])
for titulos in pesquisa_de_nome_sort_ano['title']:
    if "Romeo and Juliet" == titulos:
        print("\n Primeira pelicula 'Romeo and Juliet':",titulos)
        break





Numero de Registos Titulos - 230407

Numero de Registos Elenco - 3564650

5 primeiros registros Titulos: 
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

5 ultimos registros Titulos: 
                       title  year
230402         El lobo negro  1981
230403  Komu na Rusi zhit...  1989
230404              Senotaji  2013
230405     The Leopard Woman  1920
230406    Mio caro assassino  1972

5 primeiros registros Elenco: 
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2

In [41]:
#10 Registos mais comuns


contagem = [{'title':'','count':''}]
pesquisa_de_nome_sort_title = csv_titulos_imdb.sort_values(by=['title'])
for titulos in pesquisa_de_nome_sort_title['title'].head():
    for titulo in contagem:
        if titulo['title'] != titulos:
            contagem.append({'title':titulos,'count':1})
        elif titulo['title']== titulos:
            titulo['count'] += 1
print(contagem)

[{'title': '', 'count': ''}, {'title': '#1 Serial Killer', 'count': 2}, {'title': '#5', 'count': 2}, {'title': '#5', 'count': 2}, {'title': '#50Fathers', 'count': 2}, {'title': '#50Fathers', 'count': 2}, {'title': '#50Fathers', 'count': 2}, {'title': '#50Fathers', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#66', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'title': '#73, Shaanthi Nivaasa', 'count': 2}, {'